### ISSUE TITLE
Wrong indent on tsx file

### ISSUE THREAD

**Issue by glepnir** [MaxMEllon/vim-jsx-pretty#130]
The `|` means cursor here.  When i input `enter` the cursor jump to next line but the indent seems like wrong.
![image](https://user-images.githubusercontent.com/41671631/83426205-61558900-a461-11ea-8c8e-a9b891fc5237.png)

**Comment by yuezk** [comment]
The reason is that it couldn't decide what you would type after you pressed `Enter` after a opening tag.

For example, you could continue to input the text content

```tsx
function t() {
  return (
    <Layout>
      text here
  );
}
```
In this case, the indentation is correct.

....but you could also input the closing tag, like

```tsx
function t() {
  return (
    <Layout>
      </Layout>
  );
}
```

While in this case, the indentation is incorrect, but once you typed the `>` of the closing tag. It will correct the indentation to the expected, shown below.
![ezgif-3-5f06744b2d6a](https://user-images.githubusercontent.com/3297602/83474123-cf2f9e00-a4bd-11ea-94e3-515d62f406d5.gif)

**Comment by glepnir** [comment]
Ok Fine. i  got it.
