### ISSUE TITLE
What do you lose 'pangloss/vim-javascript'

### ISSUE THREAD

**Issue by jrock2004** [MaxMEllon/vim-jsx-pretty#76]
I am curious why its recommended to install 'pangloss/vim-javascript'. Curious to why. What are we losing or gaining?

**Comment by yuezk** [comment]
@jrock2004 

Our plugin only highlights the JSX portion of the js source file. The rest of the source file is highlighted by vim-javascript or some other vim plugins, such as `yajs.vim` etc. And yes, you don't have to use any of them to highlight the javascript syntax if you like.

I recommend using vim-javascript, because this plugin is widely used and actively maintained. I also read the source code of this plugin and found that its syntax groups are much more reasonable.

Our plugin added some [patch code](https://github.com/MaxMEllon/vim-jsx-pretty/blob/master/after/syntax/javascript.vim#L23) for different javascript syntax plugins to work with them. You can see that there only one line need to be added for vim-javascript.

Personally, I have been using this plugin all the time, and it works well.

**Comment by jrock2004** [comment]
Ah ok, so its recommended so you get full highlighting support, gotcha
