### ISSUE TITLE
Difference in highlighting colors when setting vim_jsx_pretty_highlight_close_tag

### ISSUE THREAD

**Issue by pcasaretto** [MaxMEllon/vim-jsx-pretty#89]
Output when I open a js file, then issue `:let g:vim_jsx_pretty_highlight_close_tag = 1`, followed by `:e`

<img width="922" alt="Screen Shot 2019-09-17 at 18 37 41" src="https://user-images.githubusercontent.com/817039/65081704-9e80f600-d97a-11e9-9241-4dc1224ea778.png">

Output when I open a js file while having `let g:vim_jsx_pretty_highlight_close_tag = 1` in my vimrc

<img width="922" alt="Screen Shot 2019-09-17 at 18 38 21" src="https://user-images.githubusercontent.com/817039/65081733-b22c5c80-d97a-11e9-9676-09ffea75308d.png">

**Comment by yuezk** [comment]
@pcasaretto Thanks for your feedback.

The second way is recommended since we use `hi` command to highlight the syntax group, and once a syntax group has been linked to a color group, it won't be changed unless we use the `hi!` command.

So, the dynamic change of the global variable is not recommended.

The closing tag is [highlighted](https://github.com/MaxMEllon/vim-jsx-pretty/blob/89c30c0defe8ddb31bc0d3cfa5f22f3f6d8eb24f/after/syntax/jsx_pretty.vim#L190) as `Identifier` group, and your closing tag is highlighted as a white color, so I guess that the `Identifier` group of your Vim should be the white color.

If you want to highlight the closing tag as a different color, you can try to add `hi! default link jsxCloseString <The target group>` to your vimrc.

**Comment by pcasaretto** [comment]
Thanks for the reply @yuezk !
I *really* like how the the first image looks.
I still do not understand why the two different strategies result in different colors.
Is something else in my vimrc overriding the highlighting configuration?
I'm gonna go ahead and close the issue, but I would definitely appreciate the help to reach that beautiful highlighting scheme.

**Comment by yuezk** [comment]
@pcasaretto Seems that you are using the [dracula color scheme for vim](https://github.com/dracula/vim). If you prefer the first syntax highlighting, you may need to add the following configuration in your vimrc with the highlight close tag enabled.

```vim
hi link jsxCloseString Comment
hi link jsxOpenPunct jsxPunct
```

Below is my screenshot with the above configuration.

![image](https://user-images.githubusercontent.com/3297602/65210282-3989e500-dacd-11e9-946b-03865cd48fb9.png)

**Comment by pcasaretto** [comment]
Aw yeah! Thanks for your support and for this great plugin.
